### ISSUE TITLE
MS Edge not working

### ISSUE THREAD

**Issue by rbraband** [heiseonline/embetty#26]
### General information

- `embetty` version: v1.0.5
- Node.js version: v8.9.4
- Operating system name and version: Win10 Pro 1703
- Browser name and version: Microsoft Edge 40.15063.674.0

### Steps to reproduce the behaviour

1. Install the embetty-server and the demo page 
2. Open with browser Edge

![image](https://user-images.githubusercontent.com/552979/41026878-eea81076-6975-11e8-8e85-9d34f99025ca.png)

### Expected behaviour

Working like a charm .. Chrome and FF

### Actual behaviour

Not working with MS Edge

**Comment by rbraband** [comment]
Detail information: Edge on IE11 emulation works as expected

**Comment by isabelmr** [comment]
I could reproduce this issue, any idea how to solve it? It is a quite important bug.

**Comment by mick352** [comment]
@isabelmr @rbraband : thanks for reporting it. As Edge [now uses Chromium code](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/), this issue seems to no longer apply, right? Please reply if you wish to reopen.

**Comment by mick352** [comment]
FWIW: this could be reproduced on Browserstack with Edge 18:

- Twitter seems to work
- Youtube remained black with console message:

      SCRIPT5009: SCRIPT5009: 'yt' is not defined

  but worked on reload twice.

- Vimeo seems to work, too.
