### ISSUE TITLE
What does it protect against?

### ISSUE THREAD

**Issue by SteveALee** [heiseonline/embetty#28]
Could you clarify what it protects against, and how?

What's the exact use case

thanks

**Comment by compeak** [comment]
You want to put a FunTube video on your blog.

a) You use the embed code provided by FunTube.
- Now every visitor loads stuff from FunTube.
- FunTube is able to track them on all the websites with FunTube videos embedded in them.
- FunTube builds profiles on them.
- They get funny ads at work.

b) You use embetty.
- Only people who want to watch the video load stuff from FunTube.
- FunTube cannot track people who don't watch the video.

**Comment by SteveALee** [comment]
Hadn't though of that. I think I will use on [my player](https://github.com/AlwaysInMind/aim-web-app/blob/master/client/src/components/YouTubePlayer.js) as even though is in an iframe I guess it can still track. 

I already have a server so might copy code though.
