### ISSUE TITLE
Extend documentation for event usage

### ISSUE THREAD

**Issue by rbraband** [heiseonline/embetty#30]
### General information

- `embetty` version: v1.0.5
No further information required.

I was looking for a way to check if embetty started successfully and found that event  :)
It would be good if there was a reference in the documentation to the use of the'initialized' event with code example.

`$('embetty-video').on("initialized", function () {
      //your code here
});`

Additionally I would suggest an event after clicking on'playButton' ->'activated'. 
### Steps to reproduce the behaviour
Click on 'playButton'

### Expected behaviour
Emit event 'activated'

`$('embetty-video').on("activated", function () {
      //your code here
});`

### Actual behaviour
NOP

**Comment by rbraband** [comment]
Please excuse me for not submitting this as a pull request but I realize that this is my limit;)
Therefore pure JS
```
key: "activate",
value: function () {
    var callback = this.getAttribute("activate-callback");
    if (typeof callback === "function") {
        if (!callback(this))
            return;
    } else if (typeof callback === "string") {
        if (!window[callback](this))
            return;
    }
    this.shadowRoot.innerHTML = this.impl.iframe
    this.emit("activated")
}
```

My demo Set:
```
<embetty-video type="youtube" activate-callback="embettyVideoCallback" video-id="3L4fHrIJ3A4"> </embetty-video>
<!--iframe width="640" height="480" src="{$url}?rel=0&showinfo=0&modestbranding=1" frameborder="0" allowfullscreen="1"></iframe-->
<script>
    <!--
    function embettyVideoCallback(embetty) {
        console.log('embetty activate ' + embetty.type + ': ' + embetty.videoId);
        //your code for Popup or OIL
        return true;
    }
    -->
</script>
```

// and a little play around
```
$(window).load(function() { 
  $('embetty-video').on("initialized", function () {
      console.log('embetty initialized ' + this.type + ': ' + this.videoId);
      //your code
  });
  
  $('embetty-video').on("activated", function () {
      console.log('embetty starts ' + this.type + ': ' + this.videoId);
      //your code
  });
});
```

**Comment by compeak** [comment]
@rbraband I extended [the readme](https://github.com/heiseonline/embetty#events).

**Comment by compeak** [comment]
@rbraband Please close this issue if your problem has been fixed.

**Comment by rbraband** [comment]
@compeak thy
