### ISSUE TITLE
Youtube tracked on demo page 

### ISSUE THREAD

**Issue by lslinnet** [heiseonline/embetty#31]
### General information

- `embetty` version: Latests on Demo Page
- Node.js version: ...
- Operating system name and version: Mac OSX
- Browser name and version: Firefox & Latest

### Steps to reproduce the behaviour

Load the [demo page](https://heiseonline.github.io/embetty/), press play on the youtube video.
Notice one of the calls to youtube includes a cookie

### Expected behaviour

I did not expect to be tracked.

### Actual behaviour

Here is an example of the tracking that happens. I have inserted `<private>` in places where it seems that an identifier might have been.
```
GET /api/stats/watchtime?ns=yt&el=embedded&cpn=<private>&docid=m6UOo2YGbIE&ver=2&referrer=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fm6UOo2YGbIE%3Fautoplay%3D1&cmt=2.461&plid=AAVuCz9Dj9FZjI_Z&ei=PBEZW8maIY-F7QSIyp3ACw&fmt=135&fs=0&rt=8.003&of=up5AJuQ323o9cdDjlC2o8g&euri=https%3A%2F%2Fheiseonline.github.io%2Fembetty%2F&lact=2734&cl=199484561&state=paused&vm=CAEQARgE&volume=45&c=WEB_EMBEDDED_PLAYER&cver=20180606&cplayer=UNIPLAYER&cbr=Firefox&cbrver=60.0&cos=Macintosh&cosver=10.13&autoplay=1&hl=en_US&cr=DK&len=35550.678&rtn=18&afmt=140&idpj=-4&ldpj=-7&rti=8&muted=0&st=0&et=2.461&au=und.4 HTTP/1.1
Host: www.youtube.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://www.youtube.com/embed/m6UOo2YGbIE?autoplay=1
Cookie: SID=<private>; HSID=<private>; SSID=<private>; APISID=<private>; SAPISID=<private>; CONSENT=YES+<private>; VISITOR_INFO1_LIVE=<private>; PREF=f1=50000000; LOGIN_INFO=<private>; YSC=<private>; GPS=1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by rbraband** [comment]
I can't reproduce the bug. How did you set up the server correctly?
There's some information missing. Embetty needs a server component that you need to run on your infrastructure. Can you give more?

**Comment by lslinnet** [comment]
You are right... if I set it up locally I would need both this client script and the server side setup... but I did not set it up my self, I used the online demo https://heiseonline.github.io/embetty/

**Comment by compeak** [comment]
The demo page needs to be updated to the latest release.

Embetty will not protect you after you press the play button, because the embetty server does not proxy the video content. (We need to clarify this in the docs.)

**Comment by rbraband** [comment]
Yeah .. for this I will push additional information to the user (popup or oil) with a event see #29 29

**Comment by compeak** [comment]
> Yeah .. for this I will push additional information to the user (popup or oil) with a event see #29

@rbraband Third party content could already be loading when `activated` gets triggered. You probably need to use the `click` event from the `playButton`, if you want to intercept the click on the play button to ask for consent.

**Comment by compeak** [comment]
@lslinnet Please close this issue if your problem has been fixed.

**Comment by lslinnet** [comment]
Sounds like this clarifies the misconception of this that I had, thanks for clarifying it in the documentation.
