### ISSUE TITLE
Twitter links no longer work in "new Twitter"

### ISSUE THREAD

**Issue by jonmz** [heiseonline/embetty#65]
Twitter currently advertises "Sneak a peek at the new Twitter" on its home page, giving its users the opportunity to try out their new layout.

As soon as a user activates it, the embetty-generated links in the form of
```
https://twitter.com/statuses/<tweet-id>
```
no longer work; they lead to a "Page not found" error on Twitter's site.

I have found that the link form of
```
https://twitter.com/<username>/status/<tweet-id>
```
seems to work in both "new Twitter" as well as in "legacy Twitter" (as Twitter calls it), so it might be a good idea to change the format returned by `twitterUrl()`. That format is the same that Twitter itself provides through its "Copy link to tweet" functionality so I regard it as official and stable.

**Comment by FO-nTTaX** [comment]
Just gonna mention that the new twitter is rolled out now and this is still not fixed, so now all websites using this have broken links, might be about time to get this merged
